### ISSUE TITLE
NPC should be excluded from knockback synchronization

### ISSUE THREAD

**Issue by jd07159** [CASELOAD7000/knockback-sync#32]
version: 1.3.2 release
An error message keeps spamming the console every time I hit the NPC.
```[20:49:50] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to KnockbackSync v1.3.2
java.lang.NullPointerException: Cannot invoke "me.caseload.knockbacksync.manager.PlayerData.calculateVerticalVelocity(org.bukkit.entity.Player)" because "playerData" is null
	at KnockbackSync-1.3.2.jar/me.caseload.knockbacksync.listener.PlayerDamageListener.onPlayerDamage(PlayerDamageListener.java:22) ~[KnockbackSync-1.3.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor170.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2315-2a50638]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1219) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1209) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1138) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1101) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1257) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2420) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1553) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:1041) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1235) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at Citizens-2.0.35-b3598.jar/net.citizensnpcs.nms.v1_21_R1.entity.EntityHumanNPC.hurt(EntityHumanNPC.java:253) ~[Citizens-2.0.35-b3598.jar:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1383) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2544) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$4.onAttack(ServerGamePacketListenerImpl.java:2961) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2870) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:49:50] [Server thread/ERROR]: Could not pass event PlayerVelocityEvent to KnockbackSync v1.3.2
java.lang.NullPointerException: Cannot invoke "me.caseload.knockbacksync.manager.PlayerData.getLastDamageTicks()" because "playerData" is null
	at KnockbackSync-1.3.2.jar/me.caseload.knockbacksync.listener.PlayerKnockbackListener.onPlayerVelocity(PlayerKnockbackListener.java:38) ~[KnockbackSync-1.3.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor171.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2315-2a50638]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:274) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.level.ChunkMap.newTrackerTick(ChunkMap.java:935) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:956) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:413) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:710) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1842) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1633) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1333) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by jd07159** [comment]
It has been confirmed that the modifications were made in the development build.
